apiVersion: v1
kind: Service
metadata:
  name: {{ include "admin-api.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "admin-api.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8080
