apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:6.0
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: api
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
