apiVersion: v2
name: admin-ui
description: "Admin UI microservice Helm chart"
type: application
version: 0.1.0
appVersion: "latest"
icon: https://raw.githubusercontent.com/helm/helm/main/docs/images/helm.png
